### ISSUE TITLE
are you serious?

### ISSUE THREAD

**Issue by tunnckoCore** [overlookmotel/promisify-any#1]
Promisify sync function? What about JSON.parse which is good example for sync function.
using `fn.length > 0` is ridiculous.

There have a lot tries to do that, but I'm sure it's almost impossible to detect that given function is sync or async.

try that

``` js
var promisifyAny = require('promisify-any')
var JSONParsePromise = promisifyAny(JSON.parse)

JSONParsePromise('{"foo":"bar"}')
.then(console.log)
.catch(console.error)
```

almost the same as `wrap-fn` by @matthewmueller same problem have there.

**Comment by overlookmotel** [comment]
Yes, I'm serious!

You're right that it's all but impossible to tell if a function is sync or not.

The point is that you have give `promisify-all` a hint - you tell it how many arguments there should be for the function. Then it can work out if it's an async function with a callback, or returning synchronously.

e.g.:

```
function fn1 (id) {
    // model.find() returns a promise
    return model.find( { where: { id: id } } );
}

function fn2 (id , callback) {
    // fs.readFile() uses a callback
    fs.readFile('/path/to/folder/' + id + '.txt', callback);
}

var promisify = require('promisify-any');
var fnPromisified1 = promisify(fn1, 1);
var fnPromisified2 = promisify(fn2, 1);

fnPromisified1(123).then(function(result) {
    // do something
});

fnPromisified2(123).then(function(result) {
    // do something
});

```

Both `fn1` and `fn2` are promisified.

Please note the extra argument `1` passed to promisify which indicates the number of args the function should have (not including the callback).

There's little reason why you'd want to promisify a sync function. But it can be useful in a promise-returning function to also return or throw synchronously.

In the example below, a user is loaded from the database, but records are cached in a variable, and the cached version is used first if it exists. The function can do any of:
- return a promise that is asynchronously resolved
- return a promise that is asynchronously rejected
- return a result synchronously (from the cache)
- throw synchronously

``` js
var cache = [];
function getUserFromDb(id) {
    if (!id) throw new Error('Must provide id');

    if (cache[id]) return cache[id];

    return userModel.find( { where: { id: id } } ).then(function(result) {
        if (!result) return Promise.reject(new Error('User not found'));

        cache[id] = result;
        return result;
    };
}
```

This will not work if the function returns synchronously:

``` js
getUserFromDb(123).then(function(result) {
    // do something with the result
});
```

But this will always work:

``` js
var promisify = require('promisify-any');
getUserFromDb = promisify(getUserFromDb, 1);

getUserFromDb(123).then(function(result) {
    // do something with the result
});
```

**Comment by overlookmotel** [comment]
In your example, here's the code which will work:

``` js
var promisifyAny = require('promisify-any')
var JSONParsePromise = promisifyAny(JSON.parse, 1)

JSONParsePromise('{"foo":"bar"}')
.then(console.log)
.catch(console.error)
```

Note the addition of the `1` argument to `promisifyAny()`.

Does that make more sense now?

**Comment by tunnckoCore** [comment]
Hmm.. yea. Just didn't follow the logic completely, bad day. But yea, it's still weird.
