### ISSUE TITLE
Use native promises instead of bluebird?

### ISSUE THREAD

**Issue by rstacruz** [overlookmotel/promisify-any#2]
Native promises are now in Node.js, in most modern browsers, and even in legacy ones via polyfill. Why not use it instead of co-bluebird?

**Comment by overlookmotel** [comment]
Because bluebird is much faster! See an explanation of why in the author of bluebird's comment here: http://programmers.stackexchange.com/questions/278778/why-are-native-es6-promises-slower-and-more-memory-intensive-than-bluebird

But if you want to use native promises with `promisify-any`, you can do it. Like this:

``` js
var promisify = require('promisify-any').use(Promise);
```

**Comment by overlookmotel** [comment]
I'm closing this issue but if you want to reply, please feel free - closing the issue doesn't mean I'm not happy to talk!

**Comment by overlookmotel** [comment]
I'll update the README with a note about this in the next release (which I'll be doing fairly soon to support bluebird v3)

**Comment by rstacruz** [comment]
aye, alright. I understand bluebird is faster, but I'd much rather use the default Promise implementation and override global.Promise with bluebird if I like.

also, I prefer not having Bluebird in browser builds—I'd rather save on time-to-first-load rather than a few milliseconds in promise chains.

**Comment by overlookmotel** [comment]
Ah ha yes that all makes sense. I'm mostly node-based so don't really have to think much about time-to-load.

I think I'll leave bluebird as the default, but as I said you can override that very easily with `.use(Promise)`.

Hmm... actually, come to think of it I'm not 100% sure it'll work. Do native promises have a `Promise.promisify()` method like bluebird? If not, you'd have to add a shim for it.

**Comment by overlookmotel** [comment]
Or, if native promises don't have `.promisify()`, please feel free to do a PR for the `.use()` method checking if `Promise` has a `promisify` method, and if not, making it produce one.
